/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferaybook.courses.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Lecture service. Represents a row in the &quot;lb_Lecture&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferaybook.courses.manager.model.impl.LectureModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferaybook.courses.manager.model.impl.LectureImpl</code>.
 * </p>
 *
 * @author Matteo Donnini
 * @see Lecture
 * @generated
 */
@ProviderType
public interface LectureModel extends BaseModel<Lecture>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lecture model instance should use the {@link Lecture} interface instead.
	 */

	/**
	 * Returns the primary key of this lecture.
	 *
	 * @return the primary key of this lecture
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this lecture.
	 *
	 * @param primaryKey the primary key of this lecture
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the lecture ID of this lecture.
	 *
	 * @return the lecture ID of this lecture
	 */
	public long getLectureId();

	/**
	 * Sets the lecture ID of this lecture.
	 *
	 * @param lectureId the lecture ID of this lecture
	 */
	public void setLectureId(long lectureId);

	/**
	 * Returns the company ID of this lecture.
	 *
	 * @return the company ID of this lecture
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this lecture.
	 *
	 * @param companyId the company ID of this lecture
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this lecture.
	 *
	 * @return the group ID of this lecture
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this lecture.
	 *
	 * @param groupId the group ID of this lecture
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the course ID of this lecture.
	 *
	 * @return the course ID of this lecture
	 */
	public long getCourseId();

	/**
	 * Sets the course ID of this lecture.
	 *
	 * @param courseId the course ID of this lecture
	 */
	public void setCourseId(long courseId);

	/**
	 * Returns the name of this lecture.
	 *
	 * @return the name of this lecture
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this lecture.
	 *
	 * @param name the name of this lecture
	 */
	public void setName(String name);

	/**
	 * Returns the description of this lecture.
	 *
	 * @return the description of this lecture
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this lecture.
	 *
	 * @param description the description of this lecture
	 */
	public void setDescription(String description);

	/**
	 * Returns the video link of this lecture.
	 *
	 * @return the video link of this lecture
	 */
	@AutoEscape
	public String getVideoLink();

	/**
	 * Sets the video link of this lecture.
	 *
	 * @param videoLink the video link of this lecture
	 */
	public void setVideoLink(String videoLink);

	@Override
	public Lecture cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}