/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferaybook.courses.manager.model.impl;

import com.liferaybook.courses.manager.model.Course;
import com.liferaybook.courses.manager.service.CourseLocalServiceUtil;

/**
 * The extended model base implementation for the Course service. Represents a row in the &quot;lb_Course&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CourseImpl}.
 * </p>
 *
 * @author Matteo Donnini
 * @see CourseImpl
 * @see Course
 * @generated
 */
public abstract class CourseBaseImpl extends CourseModelImpl implements Course {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a course model instance should use the <code>Course</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CourseLocalServiceUtil.addCourse(this);
		}
		else {
			CourseLocalServiceUtil.updateCourse(this);
		}
	}

}