/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferaybook.courses.manager.model.impl;

import com.liferaybook.courses.manager.model.Lecture;
import com.liferaybook.courses.manager.service.LectureLocalServiceUtil;

/**
 * The extended model base implementation for the Lecture service. Represents a row in the &quot;lb_Lecture&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LectureImpl}.
 * </p>
 *
 * @author Matteo Donnini
 * @see LectureImpl
 * @see Lecture
 * @generated
 */
public abstract class LectureBaseImpl
	extends LectureModelImpl implements Lecture {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a lecture model instance should use the <code>Lecture</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			LectureLocalServiceUtil.addLecture(this);
		}
		else {
			LectureLocalServiceUtil.updateLecture(this);
		}
	}

}